### ISSUE TITLE
Create predict() function in Client class to process fed data and create operators part of dictionary

### ISSUE THREAD

**Issue by ramyabuva** [Palashio/Libra#58]
Use Scaler fit in the preprocess function to alter data before prediction

**Comment by Palashio** [comment]
Basically, when we're using StandardScaler() in the structured_preprocesser() function, you have to fit it on the dataset. So when the user is trying to predict with their own data, they can't because we have to preprocess with a pre-fitted StandardScaler().

Thus, we have to store the StandardScaler() in a 'operators' key of the models dictionary and then built a predict() function that uses this.
