### ISSUE TITLE
Tabular Data File Support

### ISSUE THREAD

**Issue by vyathakavilocana** [Palashio/libra#69]
Something we could improve upon in terms of formats of data to be preprocessed could be an integration with Google Sheets/docs as well as an expansion enabling .tsv files.

**Comment by Palashio** [comment]
@pahuja-gor is currently developing a data_reader class and we can integrate that into there as well.

**Comment by pahuja-gor** [comment]
@vyathakavilocana @Palashio I’ll check and see if we can incorporate .tsv files into the Reader class. By Google Sheets/Docs do you mean the online document itself or the document you get when you download it to your computer?

**Comment by vyathakavilocana** [comment]
I was thinking integrating it directly perhaps with the Google Sheets API. Also, would it be possible for me to work with you on that, pahuja-gor

**Comment by Palashio** [comment]
both should be implemented. 1) the actual downloaded google docs file 2) a link to the google docs file.

**Comment by pahuja-gor** [comment]
Integrating the Google Sheets API required the use of tokens which expired after every run. Which means that the user has to retrieve/generate a new token in order to use the Google Sheets API to access a spreadsheet. 

We didn't add support for .tsv files, because we already support .csv files, which are slightly similar.
